# Generated by Django 5.0.2 on 2024-03-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd', models.IntegerField()),
                ('valor_desconto', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='back_delivery.pedido')),
            ],
        ),
    ]
