# Generated by Django 5.0.2 on 2024-03-04 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0005_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='back_delivery.produto'),
        ),
    ]
