# Generated by Django 5.0.2 on 2024-03-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0006_alter_item_pedido_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cartao', models.IntegerField()),
                ('nome_cartao', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('cvv', models.SmallIntegerField()),
                ('pag_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_delivery.pedido')),
            ],
        ),
    ]
