# Generated by Django 5.0.3 on 2024-03-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0007_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
