# Generated by Django 5.0.3 on 2024-03-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0008_usuario_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=16),
        ),
    ]
