# Generated by Django 5.0.2 on 2024-03-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0009_alter_usuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
