# Generated by Django 5.0.3 on 2024-03-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0014_alter_produto_categoria_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images'),
        ),
    ]
