# Generated by Django 4.2.7 on 2024-03-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0018_alter_produto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(blank=True, max_length=50)),
                ('logradouro_restaurante', models.CharField(max_length=50)),
                ('numero_restaurante', models.SmallIntegerField()),
                ('complemento_restaurante', models.CharField(blank=True, max_length=50, null=True)),
                ('ponto_ref_restaurante', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro_restaurante', models.CharField(max_length=50)),
                ('cidade_restaurante', models.CharField(max_length=50)),
                ('uf_restaurante', models.CharField(max_length=2)),
                ('cep_restaurante', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_delivery.restaurante'),
            preserve_default=False,
        ),
    ]
