# Generated by Django 4.2.7 on 2024-03-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0019_restaurante_produto_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_usuario',
        ),
    ]
