# Generated by Django 4.2.7 on 2024-03-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0021_remove_produto_restaurante_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_delivery.restaurante'),
            preserve_default=False,
        ),
    ]
