# Generated by Django 4.2.7 on 2024-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0022_produto_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='nome_restaurante',
            field=models.CharField(max_length=50),
        ),
    ]
