# Generated by Django 4.2.7 on 2024-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0024_categoria_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='restaurantes',
            field=models.ManyToManyField(to='back_delivery.restaurante'),
        ),
    ]
