# Generated by Django 4.2.7 on 2024-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0027_restaurante_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
