# Generated by Django 4.2.7 on 2024-03-24 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0028_alter_restaurante_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='categoria_restaurante',
        ),
    ]
