# Generated by Django 4.2.7 on 2024-03-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0029_rename_categoria_produto_categoria_restaurante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='restaurantes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria_restaurante',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='categoria_restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_delivery.categoria'),
            preserve_default=False,
        ),
    ]
