# Generated by Django 4.2.7 on 2024-03-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0032_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='descricao',
            new_name='descricao_restaurante',
        ),
    ]
