# Generated by Django 4.2.7 on 2024-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0033_rename_descricao_restaurante_descricao_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
