# Generated by Django 4.2.7 on 2024-03-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0034_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cep',
        ),
    ]
