# Generated by Django 4.2.7 on 2024-04-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0035_remove_endereco_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='cep_restaurante',
        ),
    ]
