# Generated by Django 4.2.7 on 2024-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0036_remove_restaurante_cep_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cep_restaurante',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
