# Generated by Django 4.2.7 on 2024-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0039_alter_endereco_logradouro_alter_endereco_ponto_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='ponto_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
