# Generated by Django 4.2.7 on 2024-05-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0040_alter_endereco_ponto_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images'),
        ),
    ]
