# Generated by Django 4.2.7 on 2024-05-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0042_remove_pedido_num_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_produtos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_delivery.produto'),
            preserve_default=False,
        ),
    ]
