# Generated by Django 4.2.7 on 2024-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0044_remove_pedido_pedido_produtos_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num_nota_fiscal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='serie_nota_fiscal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
