# Generated by Django 4.2.7 on 2024-05-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0045_pedido_num_nota_fiscal_pedido_serie_nota_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_usuario',
        ),
    ]
