# Generated by Django 4.2.7 on 2024-05-18 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0046_remove_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
