# Generated by Django 4.2.7 on 2024-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0049_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_compra',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
