# Generated by Django 4.2.7 on 2024-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0051_alter_pedido_data_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_compra',
            field=models.DateTimeField(),
        ),
    ]
