# Generated by Django 4.2.7 on 2024-05-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0054_alter_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_delivery.restaurante'),
        ),
    ]
