# Generated by Django 4.2.7 on 2024-05-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0055_alter_pedido_pedido_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_usuario',
            new_name='restaurante',
        ),
    ]
