# Generated by Django 4.2.7 on 2024-05-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0056_rename_pedido_usuario_pedido_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_delivery.produto'),
            preserve_default=False,
        ),
    ]
