# Generated by Django 4.2.7 on 2024-05-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0057_pedido_nome_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nome_prod',
        ),
    ]
