# Generated by Django 4.2.7 on 2024-05-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0058_remove_pedido_nome_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='back_delivery.produto'),
        ),
    ]
