# Generated by Django 4.2.7 on 2024-05-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0059_pedido_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ManyToManyField(to='back_delivery.restaurante'),
        ),
    ]
