# Generated by Django 4.2.7 on 2024-05-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0060_remove_pedido_restaurante_pedido_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_compra',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
