# Generated by Django 4.2.7 on 2024-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0068_remove_pedido_restaurante_pedido_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
