# Generated by Django 4.2.7 on 2024-05-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_delivery', '0069_pedido_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='desconto',
        ),
    ]
